### ISSUE TITLE
How do you generate the annotation corpus for Fr

### ISSUE THREAD

**Issue by Anikacyp** [YoannDupont/WiNER-fr#2]
Hi, I'm wondering how do you generate the annotation corpus for French, I also want to generate the same corpus for German, Can you tell me how do you generate it? Thanks very much.

**Comment by YoannDupont** [comment]
Hi,

Concerning the creation of the data:
- I used my own tool to annotate the corpus: https://github.com/YoannDupont/SEM
- I made a tutorial for annotating data: https://github.com/YoannDupont/SEM-tutorial
- For crawling, you might take a look at `get_month_articles.py` in this repo. It currently only works for french, but there should little modifications required to make it work for german too (if that is of interest, you will not get names such as `YYYY-MM-YY`, as I created those names with a script after annotating the data).

About the crawling part specifically:
- I'd recommend you crawl Wikinews with a dedicated tools, mine is far from perfect and you might miss some interesting stuff. I can only remember this one right now: https://github.com/psiopic2/psicrawler

Hope it helps. If you have any other question, feel free to ask!

**Comment by Anikacyp** [comment]
> Hi,
> 
> Concerning the creation of the data:
> 
> * I used my own tool to annotate the corpus: https://github.com/YoannDupont/SEM
> * I made a tutorial for annotating data: https://github.com/YoannDupont/SEM-tutorial
> * For crawling, you might take a look at `get_month_articles.py` in this repo. It currently only works for french, but there should little modifications required to make it work for german too (if that is of interest, you will not get names such as `YYYY-MM-YY`, as I created those names with a script after annotating the data).
> 
> About the crawling part specifically:
> 
> * I'd recommend you crawl Wikinews with a dedicated tools, mine is far from perfect and you might miss some interesting stuff. I can only remember this one right now: https://github.com/psiopic2/psicrawler
> 
> Hope it helps. If you have any other question, feel free to ask!

Many Thanks! It's very helpful!
